beru/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('cas/', include('cas_server.urls', namespace="cas_server")),
]

user/urls.py
#!/usr/bin/python3
# Released under GPLv3+ License
# Danial Behazdi <dani.behzi@ubuntu.com>, 2021

from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('send', views.send_code, name="send"),
    path('login', views.login, name="login"),
    path('check_otp', views.check_otp, name="check_otp"),
    path('set_username', views.set_username, name="set_username"),
    path('', views.login, name="main-page"),
    ]

user/models.py
"""
models for user app
"""
from django.db import models
from django.contrib.auth.models import UserManager, AbstractUser
from django.utils import timezone
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.


class PhoneUserManager(UserManager):
    """
    django usermanager class for loging in with phone number
    """
    def create_user(self, phone, username=None, password=None):
        user = self.model(phone=phone)
        if username:
            user.username = username
        if password:
            user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, phone, password):
        user = self.create_user(
              phone=phone,
              password=password,
               )
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractUser):
    """
    user class of user app
    """
    username = models.CharField(max_length=128, blank=True, unique=True)
    phone = PhoneNumberField(null=False, blank=False, unique=True)
    first_login = models.BooleanField(null=False, blank=False, default=True)

    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = []
    objects = PhoneUserManager()

    def __str__(self):
        return str(self.phone)

    class Meta():
        """
        meta data fro user class
        """
        db_table = 'auth_user'
        verbose_name = 'User'
        verbose_name_plural = 'Users'


class Code(models.Model):
    """
    the otp code
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    code = models.CharField(max_length=6)
    date = models.DateTimeField(default=timezone.now)

user/forms.py
#!/usr/bin/python3
# Released under GPLv3+ License
# Javad Nikbakht <javadnikbakht@mail.com>, 2021

"""
froms for user app
"""

from django import forms
from .models import User


class GetUsernameForm(forms.ModelForm):
    """
    form to get username from user
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = "نام کاربری"

    class Meta:
        """
        Meta data for class
        """
        model = User
        fields = ('username',)
        labels = {"username": ""}

user/views.py
"""
views for user app
"""
import random
import re
import string
from urllib.parse import quote_plus as quote

from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
from django.http import HttpResponse

import phonenumbers as p
from phonenumber_field import validators

from beru.settings import DEFAULT_REGION as region
from .models import User
from .sms import sms_code
from .forms import GetUsernameForm

# Create your views here.


def convert_get(request, get_in=None):
    """
    Gets GET from request and returns it as a string.
        If there is an additional argument, appends it.
    """
    if get_in is None:
        get_in = {}
    for item in request.GET:
        get_in.update({item: request.GET[item]})
    get_out = '&'.join('{}={}'.format(
        quote(item), quote(get_in[item])) for item in get_in)
    if get_out.endswith("%2F"):
        get_out = get_out[:-3]
    return get_out


def login(request):
    """
    login url view
    """
    template = 'user/login.html'
    get = convert_get(request)
    context = {'post_url': 'send?{}'.format(get)}
    return render(request, template, context)


def send_code(request):
    """
    send url view
    """
    phone = get_phone(request)
    user = get_user(phone)
    if sms_code(user):
        get_in = {'phone': phone}
        get = convert_get(request, get_in)
        if user.first_login:
            return redirect('check_otp?{}/'.format(get))
        return redirect('cas/login?{}'.format(get))
    return redirect('cas/login')


def get_phone(request):
    """
    returns phone number from request
    """
    if request.method == "POST" and 'phone' in request.POST:
        phone = request.POST.get('phone', '')
    else:
        phone = request.GET.get('phone')
    phone = p.format_number(p.parse(phone, region), p.PhoneNumberFormat.E164)
    if not is_valid(phone):
        return HttpResponse('Send a valid phone number', status=400)
    return phone


def get_user(phone):
    """
    returns user from phone number
    """
    try:
        user = User.objects.get(phone=phone)
    except User.DoesNotExist:
        username = generate_username()
        user = User.objects.create_user(phone=phone, username=username,)
    return user


def generate_username():
    """
    generates a random username
    """
    alnum = string.ascii_lowercase+string.digits
    while True:
        username = ''.join(random.choices(alnum, k=20))
        if username.isdigit():
            continue
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            break
    return username


def is_valid(phone):
    """
    checks given phone number against 'phonenumbers' library
    """
    try:
        validators.validate_international_phonenumber(phone)
    except ValidationError:
        return False
    return True


def check_otp(request):
    """
    check_otp url view
    """
    if request.method == "POST":
        phone = get_phone(request)
        user = get_user(phone)
        code = request.POST.get('password')
        user_authenticated = authenticate(phone=user.phone, code=code)
        get = convert_get(request)
        if user_authenticated and user.first_login:
            return redirect('set_username?{}/'.format(get))
        return redirect('/cas/login')
    return render(request, 'user/get_otp.html')


def set_username(request):
    """
    set_username url view
    """
    phone = get_phone(request)
    user = get_user(phone)
    if request.method == 'POST':
        form = GetUsernameForm(request.POST, instance=user)
        if form.is_valid():
            form_data = form.save(commit=False)
            form_data.user = request.user
            form_data.save()
            user.first_login = False
            user.save()
            get = convert_get(request)
            if sms_code(user):
                return redirect('/cas/login?{}'.format(get))
            phone_pattern = r"phone=%2B?\d{12}"
            get = re.sub(phone_pattern, '', get)
            return redirect('/cas/login?{}'.format(get))
        form = GetUsernameForm()
        repeated_username_msg = "نام کاربری وارد شده صحیح نیست"
        context = {
            'form': form,
            'bad_msg': repeated_username_msg,
        }
        return render(request, 'user/set_username.html', context)
    form = GetUsernameForm()
    return render(request, 'user/set_username.html', {'form': form, })

user/templates/user/cas_login.html
{% load static %}

{% block content %}
<head>
  <title>Beru - Authentication</title>
  
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">
  <link href='https://cdn.fontcdn.ir/Font/Persian/Shabnam/Shabnam.css' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" >

  <!-- Style -->
  <link rel="stylesheet" href="{% static 'user/css/style.css' %}">
</head>
<body style="background-image: url({% static 'user/images/lake.jpg' %});">
  <div class="container h-100 cover fixed">
    <div class="d-flex justify-content-center h-100">
      <div class="user_card">
        <div class="d-flex justify-content-center">
          <div class="brand_logo_container">
            <img src="{% static 'user/images/logo300.png' %}" class="brand_logo" alt="Logo">
          </div>
        </div>
        <div class="d-flex justify-content-center form_container">
          {% if 'phone' not in request.GET %}
            <script type="text/javascript">
              location.replace("{% url 'user:login' %}"+ location.search);
            </script>
            {% csrf_token %}
            <div class="form-group">
              <label class="control-label" for="id_phone">شماره تلفن</label>
              <input type="tel" name="phone" autofocus="autofocus" class="form-control" placeholder="شماره تلفن" required id="id_phone" />
            </div>
          {% else %}
            <form class="form-signin" method="post" id="login_form" {% if post_url %} action="{{post_url}}" {% endif %}>
              {% csrf_token %}
              {% include "user/form.html" %}
              <input type="hidden" name="username" id="id_username" value="{{ request.GET.phone }}" />

              <div class="input-group mb-3">
                <div class="input-group-append">
                  <span class="input-group-text"><i class="fas fa-lock"></i></span>
                </div>
                <input type="text" name="password" class="form-control input_user" value="" placeholder="کد تأیید" required id="id_password">
              </div>
              
              {% if auto_submit %}<noscript>{% endif %}
              <button class="btn login_btn" type="submit">ورود</button>
              {% if auto_submit %}</noscript>{% endif %}
            </form>
          {% endif %}
      </div>
    </div>
  </div>
  <script src="{% static 'user/js/main.js' %}"></script>
</body> 
{% endblock %}

user/templates/user/form.html
{% load cas_server %}

{% for error in form.non_field_errors %}
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    {{error}}
  </div>
{% endfor %}

{% for field in form %}{% if field|is_hidden %}{{field}}{% endif %}{% endfor %}

user/templates/user/get_otp.html
{% load static %}

{% block content %}
<head>
  <title>Beru - Authentication</title>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">
  <link href='https://cdn.fontcdn.ir/Font/Persian/Shabnam/Shabnam.css' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" >

  <!-- Style -->
  <link rel="stylesheet" href="{% static 'user/css/style.css' %}">
</head>
<body style="background-image: url({% static 'user/images/lake.jpg' %});">
  <div class="container h-100 cover fixed">
    <div class="d-flex justify-content-center h-100">
      <div class="user_card">
        <div class="d-flex justify-content-center">
          <div class="brand_logo_container">
            <img src="{% static 'user/images/logo300.png' %}" class="brand_logo" alt="Logo">
          </div>
        </div>
        <div class="d-flex justify-content-center form_container">
          <form class="form-signin" method="post" id="login_form" {% if post_url %} action="{{post_url}}" {% endif %}>
              {% csrf_token %}
              {% include "user/form.html" %}
              <input type="hidden" name="username" id="id_username" value="{{ request.GET.phone }}" />

              <div class="input-group mb-3">
                <div class="input-group-append">
                  <span class="input-group-text"><i class="fas fa-lock"></i></span>
                </div>
                <input type="text" name="password" class="form-control input_user" value="" placeholder="کد تأیید" required id="id_password">
              </div>

              {% if auto_submit %}<noscript>{% endif %}
              <button class="btn login_btn" type="submit">تنظیم نام کاربری</button>
              {% if auto_submit %}</noscript>{% endif %}
          </form>

      </div>
    </div>
  </div>
  <script src="{% static 'user/js/main.js' %}"></script>
</body>
{% endblock %}

user/templates/user/login.html
{% load static %}

{% block content %}
  <head>
    <title>Beru - Authentication</title>
    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">
    <link href='https://cdn.fontcdn.ir/Font/Persian/Shabnam/Shabnam.css' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" >

    <!-- Style -->
    <link rel="stylesheet" href="{% static 'user/css/style.css' %}">
  </head>
  <body style="background-image: url({% static 'user/images/lake.jpg' %});">
    <div class="container h-100 cover fixed">
      <div class="d-flex justify-content-center h-100">
        <div class="user_card">
          <div class="d-flex justify-content-center">
            <div class="brand_logo_container">
              <img src="{% static 'user/images/logo300.png' %}" class="brand_logo" alt="Logo">
            </div>
          </div>
          <div class="d-flex justify-content-center form_container">
            <form class="form-signin" method="post" id="login_form" style="margin: auto;"
              {% if post_url %} action="{{post_url}}"{% endif %}>
              {% csrf_token %}
              <div class="input-group mb-3">
                <div class="input-group-append">
                  <span class="input-group-text"><i class="fas fa-phone"></i></span>
                </div>
                <input type="tel" name="phone" class="form-control input_user" value="" placeholder="شماره تلفن" autofocus="autofocus" id="id_phone" required >
              </div>
              {% if auto_submit %}<noscript>{% endif %}
                <button type="submit" name="button" class="btn login_btn">ثبت</button>
              {% if auto_submit %}</noscript>{% endif %}                
            </form>
          </div>
        </div>
      </div>
    </div>
    <script src="{% static 'user/js/main.js' %}"></script>
  </body> 
{% endblock %}

user/templates/user/set_username.html
{% load static %}
{% block content %}
<head>
  <title>Beru - Authentication</title>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">
  <link href='https://cdn.fontcdn.ir/Font/Persian/Shabnam/Shabnam.css' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" >

  <!-- Style -->
  <link rel="stylesheet" href="{% static 'user/css/style.css' %}">
</head>
<body style="background-image: url({% static 'user/images/lake.jpg' %});">
  <div class="container h-100 cover fixed">
    <div class="d-flex justify-content-center h-100">
      <div class="user_card">
        <div class="d-flex justify-content-center">
          <div class="brand_logo_container">
            <img src="{% static 'user/images/logo300.png' %}" class="brand_logo" alt="Logo">
          </div>
        </div>
        <div class="d-flex justify-content-center form_container">
          <form method="POST" style="direction:rtl;">
            {% csrf_token %}
            <fieldset class="form-group" >
              {{ form }}
            </fieldset>
            <div class="form-group">
              <button class="btn login_btn" type="submit">ثبت و بازگشت</button>
            </div>
          </form>
      </div>
    </div>
  </div>
  <script src="{% static 'user/js/main.js' %}"></script>
</body>
{% endblock %}